# -*- coding: utf-8 -*-
"""ASSIGMENTipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c-bYPZKFKEsId6Ka_CbWozURrMhtB7Ew
"""

fruits = ["Apple", "Banana", "Mango"]

print(fruits)

fruits = ["Apple", "Banana", "Mango"]
fruits[1] = "Orange"
print(fruits)

numbers = [10, 20, 20, 30, 10]
print(numbers)

